import { describe, it, expect, vi, beforeEach } from 'vitest'
import { newIdempotencyKey } from '../idempotency.utils'

describe('newIdempotencyKey', () => {
  beforeEach(() => {
    vi.restoreAllMocks()
  })

  it('returns the value generated by crypto.randomUUID', () => {
    vi.spyOn(globalThis.crypto, 'randomUUID').mockReturnValue('uuid-1' as `${string}-${string}-${string}-${string}-${string}`)

    expect(newIdempotencyKey()).toBe('uuid-1')
  })

  it('calls crypto.randomUUID each time', () => {
    const randomUUIDSpy = vi
      .spyOn(globalThis.crypto, 'randomUUID')
      .mockReturnValueOnce('uuid-1' as `${string}-${string}-${string}-${string}-${string}`)
      .mockReturnValueOnce('uuid-2' as `${string}-${string}-${string}-${string}-${string}`)

    expect(newIdempotencyKey()).toBe('uuid-1')
    expect(newIdempotencyKey()).toBe('uuid-2')
    expect(randomUUIDSpy).toHaveBeenCalledTimes(2)
  })
})
